-- Databricks notebook source

-- COMMAND ----------

CREATE CATALOG IF NOT EXISTS ng_banking_lakehouse;

-- COMMAND ----------

CREATE SCHEMA IF NOT EXISTS ng_banking_lakehouse.transaction_raw;

-- COMMAND ----------

CREATE SCHEMA IF NOT EXISTS ng_banking_lakehouse.transaction_curated;

-- COMMAND ----------

CREATE SCHEMA IF NOT EXISTS ng_banking_lakehouse.transaction_mart;

-- Raw transaction_events is created by Auto Loader in notebook 01.


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_curated.transaction_mapping(
 TRN_CODE STRING,MODULE STRING,PRODUCT STRING,PRIORITY INT,
 MAP_MODULE STRING,MODULE_CATEGORY STRING,MODULE_DESCRIPTION STRING,
 TRANSACTION_CATEGORY STRING,TRANSACTION_DESCRIPTION STRING,
 IS_REVERSAL_CODE BOOLEAN,ACTIVE_FLAG STRING) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_curated.etl_watermark(
 PIPELINE_NAME STRING,LAST_RAW_INGEST_TIMESTAMP TIMESTAMP,LAST_RUN_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_curated.pipeline_processing_log(
 PIPELINE_RUN_ID STRING,PIPELINE_NAME STRING,RUN_START_TIMESTAMP TIMESTAMP,RUN_END_TIMESTAMP TIMESTAMP,
 MIN_RAW_INGEST_TIMESTAMP TIMESTAMP,MAX_RAW_INGEST_TIMESTAMP TIMESTAMP,RECORDS_RECEIVED BIGINT,
 VALID_RECORDS BIGINT,INVALID_RECORDS BIGINT,MIN_TRANSACTION_DATE DATE,MAX_TRANSACTION_DATE DATE,STATUS STRING) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_curated.pipeline_affected_dates(
 PIPELINE_RUN_ID STRING,PIPELINE_NAME STRING,TRANSACTION_DATE DATE,TRANSACTION_MONTH_ID INT,
 CREATED_TIMESTAMP TIMESTAMP,PROCESSED_FLAG BOOLEAN,PROCESSED_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_curated.pipeline_dq_results(
 PIPELINE_RUN_ID STRING,PIPELINE_NAME STRING,CHECK_NAME STRING,SEVERITY STRING,
 RESULT_VALUE DOUBLE,PASSED BOOLEAN,CHECKED_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_curated.transaction_rejected(
 PIPELINE_RUN_ID STRING,TRANSACTION_KEY STRING,TRN_REF_NO STRING,AC_NO STRING,TRN_CODE STRING,MODULE STRING,
 DRCR_IND STRING,LCY_AMOUNT DECIMAL(20,3),TRANSACTION_DATE DATE,REJECTION_REASON STRING,
 SOURCE_FILE_NAME STRING,RAW_INGEST_TIMESTAMP TIMESTAMP,REJECTED_TIMESTAMP TIMESTAMP) USING DELTA;

-- Create the curated table with the final business model.

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_curated.transaction_entries(
 TRANSACTION_KEY STRING,STREAM_COMPOSIT_ID STRING,STREAM_TABLE_ID STRING,STREAM_UPDATE_TIMESTAMP TIMESTAMP,
 YEAR_MONTH_ID INT,AFFILIATE_ID STRING,TRN_REF_NO STRING,EVENT_SR_NO INT,EVENT STRING,AC_BRANCH STRING,AC_NO STRING,
 AC_CCY STRING,DRCR_IND STRING,TRANSACTION_DIRECTION STRING,TRANSACTION_SIGN STRING,TRN_CODE STRING,AMOUNT_TAG STRING,
 FCY_AMOUNT DECIMAL(20,3),EXCH_RATE DECIMAL(18,6),SOURCE_LCY_AMOUNT DECIMAL(20,3),LCY_AMOUNT DECIMAL(20,3),
 ABS_LCY_AMOUNT DECIMAL(20,3),NET_SIGNED_AMOUNT DECIMAL(20,3),IS_NEGATIVE_AMOUNT BOOLEAN,IS_REVERSAL_CANDIDATE BOOLEAN,
 RELATED_CUSTOMER STRING,RELATED_ACCOUNT STRING,RELATED_REFERENCE STRING,MIS_FLAG STRING,MIS_HEAD STRING,TRN_DATE_KEY STRING,
 TRN_DT STRING,TRANSACTION_DATE DATE,VALUE_DT STRING,VALUE_DATE DATE,TXN_INIT_DATE STRING,FINANCIAL_CYCLE STRING,
 PERIOD_CODE STRING,INSTRUMENT_CODE STRING,BANK_CODE STRING,TYPE STRING,CATEGORY STRING,CUST_GL STRING,MODULE STRING,
 MAP_MODULE STRING,MODULE_CATEGORY STRING,MODULE_DESCRIPTION STRING,CLASSIFICATION_STATUS STRING,AC_ENTRY_SR_NO INT,IB STRING,
 FLG_POSITION_STATUS STRING,GLMIS_UPDATE_FLAG STRING,USER_ID STRING,CURR_NO INT,BATCH_NO STRING,PRINT_STAT STRING,
 PRODUCT_ACCRUAL STRING,AUTH_ID STRING,PRODUCT STRING,GLMIS_VAL_UPD_FLAG STRING,EXTERNAL_REF_NO STRING,DONT_SHOWIN_STMT STRING,
 IC_BAL_INCLUSION STRING,AML_EXCEPTION STRING,ORIG_PNL_GL STRING,STMT_DT STRING,NTRY_SEQ_NO INT,VIRTUAL_AC_NO STRING,
 CLAIM_AMOUNT DECIMAL(20,3),SAVE_TIMESTAMP_PARSED TIMESTAMP,AUTH_TIMESTAMP_PARSED TIMESTAMP,GRP_REF_NO STRING,
 PRODUCT_PROCESSOR STRING,RELATED_AC_ENTRY_SR_NO STRING,LOADDATE STRING,SOURCE_FILE_NAME STRING,SOURCE_FILE_PATH STRING,
 SOURCE_SYSTEM STRING,RAW_INGEST_TIMESTAMP TIMESTAMP,PIPELINE_RUN_ID STRING,CREATED_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_mart.daily_transaction_activity(
 TRANSACTION_DATE DATE,AFFILIATE_ID STRING,AC_BRANCH STRING,AC_CCY STRING,TRANSACTION_COUNT BIGINT,UNIQUE_TRANSACTION_COUNT BIGINT,
 UNIQUE_ACCOUNT_COUNT BIGINT,UNIQUE_CUSTOMER_COUNT BIGINT,CREDIT_COUNT BIGINT,TOTAL_CREDIT_AMOUNT DECIMAL(38,3),DEBIT_COUNT BIGINT,
 TOTAL_DEBIT_AMOUNT DECIMAL(38,3),NET_TRANSACTION_AMOUNT DECIMAL(38,3),AVERAGE_TRANSACTION_AMOUNT DECIMAL(38,3),MIN_TRANSACTION_AMOUNT DECIMAL(38,3),MAX_TRANSACTION_AMOUNT DECIMAL(38,3),
 UNIQUE_TRANSACTION_CODES BIGINT,UNIQUE_PRODUCTS BIGINT,UNIQUE_TRANSACTION_CATEGORIES BIGINT,NEGATIVE_AMOUNT_COUNT BIGINT,NEGATIVE_AMOUNT_VALUE DECIMAL(38,3),
 REVERSAL_CANDIDATE_COUNT BIGINT,REVERSAL_CANDIDATE_AMOUNT DECIMAL(38,3),FIRST_TRANSACTION_TIMESTAMP TIMESTAMP,LAST_TRANSACTION_TIMESTAMP TIMESTAMP,MART_LOAD_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_mart.account_transaction_activity(
 AC_NO STRING,RELATED_CUSTOMER STRING,AFFILIATE_ID STRING,AC_CCY STRING,TRANSACTION_MONTH_ID INT,TRANSACTION_COUNT BIGINT,UNIQUE_TRANSACTION_COUNT BIGINT,
 ACTIVE_TRANSACTION_DAYS BIGINT,CREDIT_COUNT BIGINT,TOTAL_CREDIT_AMOUNT DECIMAL(38,3),DEBIT_COUNT BIGINT,TOTAL_DEBIT_AMOUNT DECIMAL(38,3),NET_TRANSACTION_AMOUNT DECIMAL(38,3),
 AVERAGE_TRANSACTION_AMOUNT DECIMAL(38,3),MIN_TRANSACTION_AMOUNT DECIMAL(38,3),MAX_TRANSACTION_AMOUNT DECIMAL(38,3),FIRST_TRANSACTION_DATE DATE,LAST_TRANSACTION_DATE DATE,
 UNIQUE_BRANCHES_USED BIGINT,UNIQUE_TRANSACTION_CODES BIGINT,UNIQUE_PRODUCTS BIGINT,UNIQUE_TRANSACTION_CATEGORIES BIGINT,REVERSAL_CANDIDATE_COUNT BIGINT,REVERSAL_CANDIDATE_AMOUNT DECIMAL(38,3),MART_LOAD_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_mart.branch_transaction_activity(
 TRANSACTION_DATE DATE,AFFILIATE_ID STRING,AC_BRANCH STRING,TRANSACTION_COUNT BIGINT,UNIQUE_TRANSACTION_COUNT BIGINT,UNIQUE_ACCOUNT_COUNT BIGINT,UNIQUE_CUSTOMER_COUNT BIGINT,
 CREDIT_COUNT BIGINT,TOTAL_CREDIT_AMOUNT DECIMAL(38,3),DEBIT_COUNT BIGINT,TOTAL_DEBIT_AMOUNT DECIMAL(38,3),NET_TRANSACTION_AMOUNT DECIMAL(38,3),AVERAGE_TRANSACTION_AMOUNT DECIMAL(38,3),MAX_TRANSACTION_AMOUNT DECIMAL(38,3),
 UNIQUE_PRODUCTS BIGINT,UNIQUE_TRANSACTION_CODES BIGINT,UNIQUE_TRANSACTION_CATEGORIES BIGINT,REVERSAL_CANDIDATE_COUNT BIGINT,REVERSAL_CANDIDATE_AMOUNT DECIMAL(38,3),MART_LOAD_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_mart.transaction_code_activity(
 TRANSACTION_DATE DATE,TRN_CODE STRING,TRANSACTION_CATEGORY STRING,MODULE STRING,MAP_MODULE STRING,AC_CCY STRING,TRANSACTION_COUNT BIGINT,UNIQUE_TRANSACTION_COUNT BIGINT,UNIQUE_ACCOUNT_COUNT BIGINT,
 CREDIT_COUNT BIGINT,DEBIT_COUNT BIGINT,TOTAL_CREDIT_AMOUNT DECIMAL(38,3),TOTAL_DEBIT_AMOUNT DECIMAL(38,3),NET_TRANSACTION_AMOUNT DECIMAL(38,3),AVERAGE_TRANSACTION_AMOUNT DECIMAL(38,3),MIN_TRANSACTION_AMOUNT DECIMAL(38,3),MAX_TRANSACTION_AMOUNT DECIMAL(38,3),
 NEGATIVE_AMOUNT_COUNT BIGINT,NEGATIVE_AMOUNT_VALUE DECIMAL(38,3),REVERSAL_CANDIDATE_COUNT BIGINT,REVERSAL_CANDIDATE_AMOUNT DECIMAL(38,3),MART_LOAD_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_mart.transaction_category_activity(
 TRANSACTION_DATE DATE,TRANSACTION_CATEGORY STRING,AFFILIATE_ID STRING,AC_CCY STRING,TRANSACTION_COUNT BIGINT,UNIQUE_TRANSACTION_COUNT BIGINT,UNIQUE_ACCOUNT_COUNT BIGINT,UNIQUE_BRANCH_COUNT BIGINT,
 CREDIT_COUNT BIGINT,DEBIT_COUNT BIGINT,TOTAL_CREDIT_AMOUNT DECIMAL(38,3),TOTAL_DEBIT_AMOUNT DECIMAL(38,3),NET_TRANSACTION_AMOUNT DECIMAL(38,3),AVERAGE_TRANSACTION_AMOUNT DECIMAL(38,3),
 NEGATIVE_AMOUNT_COUNT BIGINT,NEGATIVE_AMOUNT_VALUE DECIMAL(38,3),REVERSAL_CANDIDATE_COUNT BIGINT,REVERSAL_CANDIDATE_AMOUNT DECIMAL(38,3),MART_LOAD_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

CREATE TABLE IF NOT EXISTS ng_banking_lakehouse.transaction_mart.aml_exception_activity(
 TRANSACTION_DATE DATE,AFFILIATE_ID STRING,AC_BRANCH STRING,AC_CCY STRING,EXCEPTION_TRANSACTION_COUNT BIGINT,
 AML_FLAGGED_COUNT BIGINT,HIGH_VALUE_COUNT BIGINT,TOTAL_EXCEPTION_AMOUNT DECIMAL(38,3),MAX_EXCEPTION_AMOUNT DECIMAL(38,3),
 UNIQUE_ACCOUNTS_FLAGGED BIGINT,UNIQUE_TRANSACTION_CODES BIGINT,HIGH_VALUE_THRESHOLD_LCY DECIMAL(20,3),MART_LOAD_TIMESTAMP TIMESTAMP) USING DELTA;


-- COMMAND ----------

MERGE INTO ng_banking_lakehouse.transaction_curated.etl_watermark t
USING (SELECT 'ng_banking_transaction_lakehouse_pipeline' PIPELINE_NAME,TIMESTAMP('1900-01-01') LAST_RAW_INGEST_TIMESTAMP,TIMESTAMP('1900-01-01') LAST_RUN_TIMESTAMP) s
ON t.PIPELINE_NAME=s.PIPELINE_NAME
WHEN NOT MATCHED THEN INSERT *;
