SELECT DRCR_IND,TRANSACTION_SIGN,COUNT(*) RECORD_COUNT FROM ng_banking_lakehouse.transaction_curated.transaction_entries GROUP BY DRCR_IND,TRANSACTION_SIGN;
SELECT IS_NEGATIVE_AMOUNT,COUNT(*) RECORD_COUNT,SUM(ABS_LCY_AMOUNT) ABS_VALUE FROM ng_banking_lakehouse.transaction_curated.transaction_entries GROUP BY IS_NEGATIVE_AMOUNT;
SELECT TRN_CODE,MODULE,MAP_MODULE,MODULE_CATEGORY,MODULE_DESCRIPTION,TRANSACTION_CATEGORY,CLASSIFICATION_STATUS,COUNT(*) RECORD_COUNT FROM ng_banking_lakehouse.transaction_curated.transaction_entries GROUP BY TRN_CODE,MODULE,MAP_MODULE,MODULE_CATEGORY,MODULE_DESCRIPTION,TRANSACTION_CATEGORY,CLASSIFICATION_STATUS ORDER BY RECORD_COUNT DESC;
SELECT TRN_CODE,MODULE,PRODUCT,DRCR_IND,COUNT(*) RECORD_COUNT FROM ng_banking_lakehouse.transaction_curated.transaction_entries WHERE CLASSIFICATION_STATUS='UNMAPPED' GROUP BY TRN_CODE,MODULE,PRODUCT,DRCR_IND ORDER BY RECORD_COUNT DESC;
SELECT TRN_CODE,MODULE,DRCR_IND,MAP_MODULE,MODULE_CATEGORY,MODULE_DESCRIPTION,COUNT(*) RECORD_COUNT FROM ng_banking_lakehouse.transaction_curated.transaction_entries WHERE DRCR_IND='D' AND MODULE_CATEGORY='DEPOSIT' GROUP BY TRN_CODE,MODULE,DRCR_IND,MAP_MODULE,MODULE_CATEGORY,MODULE_DESCRIPTION ORDER BY RECORD_COUNT DESC;
SELECT TRN_CODE,MODULE,MAP_MODULE,DRCR_IND,COUNT(*) RECORD_COUNT,SUM(ABS_LCY_AMOUNT) AMOUNT FROM ng_banking_lakehouse.transaction_curated.transaction_entries WHERE IS_NEGATIVE_AMOUNT GROUP BY TRN_CODE,MODULE,MAP_MODULE,DRCR_IND ORDER BY RECORD_COUNT DESC;

-- Trend of the enforced quality-gate checks (notebook 04b) over the last 30 runs.
SELECT PIPELINE_RUN_ID,CHECK_NAME,SEVERITY,RESULT_VALUE,PASSED,CHECKED_TIMESTAMP
FROM ng_banking_lakehouse.transaction_curated.pipeline_dq_results
ORDER BY CHECKED_TIMESTAMP DESC LIMIT 200;

-- Where AML/high-value exceptions are concentrated (mart 6).
SELECT * FROM ng_banking_lakehouse.transaction_mart.aml_exception_activity
ORDER BY TRANSACTION_DATE DESC, TOTAL_EXCEPTION_AMOUNT DESC;
